version: '3'

services:
  postgres:
    image: postgres:10-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
    - pgdata:/var/lib/postgresql/data
  search_engine:
    image: search_engine
    build: .
    ports:
    - 5000:5000
    environment:
      FLASK_DEBUG: 1
    volumes:
    - ./:/search_engine
    depends_on:
    - postgres

volumes:
  pgdata: {}