version: '3'

services:
  postgres:
    image: postgres:10-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
    - pgdata:/var/lib/postgresql/data
  rabbit:
    image: rabbitmq:3-alpine
  crawler:
    image: se/crawler
    build: 
      context: .
      dockerfile: Dockerfile-crawler
    command: "http://www.example.com"
    volumes:
    - ./:/search_engine
    depends_on:
    - postgres
    - rabbit
  web:
    image: se/web
    build: 
      context: .
      dockerfile: Dockerfile-web
    command: --reload
    ports:
    - 8000:8000
    environment:
      FLASK_DEBUG: 1
    volumes:
    - ./:/search_engine
    depends_on:
    - postgres

volumes:
  pgdata: {}